export const FEATURES = [
  {
    id: 'reversal',
    label: 'Reversal Scanner',
    icon: '🔄',
    status: 'live',
    description: 'Multi-factor reversal signal engine.',
    subOptions: [
      { id: 'analyze',   label: '🔍 Single Stock', icon: '🔍', path: '/reversal/analyze' },
      { id: 'sectors',   label: '🗂 Sector Scan',  icon: '🗂', path: '/reversal/sectors' },
      { id: 'watchlist', label: '📋 Watchlist',    icon: '📋', path: '/reversal/watchlist' },
      { id: 'macro',     label: '🌍 Macro View',   icon: '🌍', path: '/reversal/macro' },
    ],
  },
  {
    id: 'options',
    label: 'Options Analysis',
    icon: '📋',
    status: 'live',
    description: 'Live options chain, Greeks, IV skew, unusual activity.',
    subOptions: [
      { id: 'overview', label: '🏠 Overview',        icon: '🏠', path: '/options/overview' },
      { id: 'chain',    label: '⛓ Chain',            icon: '⛓', path: '/options/chain' },
      { id: 'unusual',  label: '🚨 Unusual Activity', icon: '🚨', path: '/options/unusual' },
      { id: 'skew',     label: '📐 IV Skew',          icon: '📐', path: '/options/skew' },
    ],
  },
  {
    id: 'earnings',
    label: 'Earnings Calendar',
    icon: '📅',
    status: 'live',
    description: 'Upcoming earnings with expected moves and EPS history.',
    subOptions: [
      { id: 'calendar', label: '📅 Calendar',         icon: '📅', path: '/earnings/calendar' },
      { id: 'analysis', label: '📊 Earnings Analysis', icon: '📊', path: '/earnings/analysis' },
    ],
  },
  {
    id: 'technical',
    label: 'Technical Analysis',
    icon: '📈',
    status: 'live',
    description: 'Chart patterns, support/resistance levels, momentum signals, and screener.',
    subOptions: [
      { id: 'indicators', label: '📊 Indicators',         icon: '📊', path: '/technical/indicators' },
      { id: 'patterns',   label: '🔍 Chart Patterns',     icon: '🔍', path: '/technical/patterns' },
      { id: 'levels',     label: '📏 Support/Resistance', icon: '📏', path: '/technical/levels' },
      { id: 'screener',   label: '🔎 Screener',           icon: '🔎', path: '/technical/screener' },
    ],
  },
  {
    id: 'fundamental',
    label: 'Fundamental Analysis',
    icon: '🏦',
    status: 'live',
    description: 'Valuation ratios, growth scores, financial health, and fundamental screener.',
    subOptions: [
      { id: 'valuation', label: '💹 Valuation',     icon: '💹', path: '/fundamental/valuation' },
      { id: 'growth',    label: '📈 Growth Score',  icon: '📈', path: '/fundamental/growth' },
      { id: 'health',    label: '🏥 Quality Score', icon: '🏥', path: '/fundamental/health' },
      { id: 'screener',  label: '🔎 Screener',      icon: '🔎', path: '/fundamental/screener' },
    ],
  },
  {
    id: 'sentiment',
    label: 'Market Sentiment',
    icon: '🧠',
    status: 'live',
    description: 'Fear & Greed index built from VIX, momentum, PCR, safe haven demand, junk bonds, breadth, and price strength.',
    subOptions: [
      { id: 'dashboard', label: '🧠 Dashboard', icon: '🧠', path: '/sentiment/dashboard' },
    ],
  },
  {
    id: 'insider',
    label: 'Insider Tracker',
    icon: '👁',
    status: 'live',
    description: 'SEC Form 4 insider buying and selling — open market purchases and cluster signals.',
    subOptions: [
      { id: 'feed',    label: '📋 Transaction Feed', icon: '📋', path: '/insider/feed' },
      { id: 'cluster', label: '🎯 Cluster Buys',     icon: '🎯', path: '/insider/cluster' },
    ],
  },
  {
    id: 'smart_money',
    label: 'Smart Money Scanner',
    icon: '💰',
    status: 'live',
    description: 'Top 50 stocks ranked by options flow, insider buying, and institutional positioning.',
    subOptions: [
      { id: 'scanner', label: '🔍 Scanner', icon: '🔍', path: '/smart_money/scanner' },
    ],
  },
  {
    id: 'ai_agent',
    label: 'AI Research Agent',
    icon: '🤖',
    status: 'live',
    description: 'AI-powered market research — ticker summaries, deep analysis, interactive chat, and Bull vs Bear debate.',
    subOptions: [
      { id: 'summary',  label: '📝 AI Summary',    icon: '📝', path: '/ai_agent/summary' },
      { id: 'research', label: '🔬 Deep Research',  icon: '🔬', path: '/ai_agent/research' },
      { id: 'chat',     label: '💬 Research Chat',  icon: '💬', path: '/ai_agent/chat' },
      { id: 'debate',   label: '⚔ Bull vs Bear',   icon: '⚔',  path: '/ai_agent/debate' },
    ],
  },
  {
    id: 'screener',
    label: 'Multi-Factor Screener',
    icon: '🔭',
    status: 'live',
    description: 'Unified screener combining technical, smart money, fundamental, and sentiment signals into one composite score.',
    subOptions: [
      { id: 'screen',    label: '🔭 Screener',    icon: '🔭', path: '/screener/screen' },
      { id: 'score',     label: '🎯 Single Score', icon: '🎯', path: '/screener/score' },
      { id: 'scheduler', label: '⏰ Scheduler',    icon: '⏰', path: '/screener/scheduler' },
    ],
  },
  {
    id: 'sentiment_ai',
    label: 'AI Sentiment',
    icon: '🧬',
    status: 'live',
    description: 'FinBERT-powered sentiment analysis on news headlines, earnings text, and custom input.',
    subOptions: [
      { id: 'news',    label: '📰 News Sentiment', icon: '📰', path: '/sentiment_ai/news' },
      { id: 'analyze', label: '🧬 Text Analyzer',  icon: '🧬', path: '/sentiment_ai/analyze' },
      { id: 'compare', label: '⚖ Ticker Compare', icon: '⚖',  path: '/sentiment_ai/compare' },
    ],
  },
  {
    id: 'congress',
    label: 'Congress Tracker',
    icon: '🏛',
    status: 'live',
    description: 'Congressional stock trades — STOCK Act disclosures from House and Senate members.',
    subOptions: [
      { id: 'feed',    label: '📋 Trade Feed',   icon: '📋', path: '/congress/feed' },
      { id: 'members', label: '👤 Top Members',  icon: '👤', path: '/congress/members' },
      { id: 'tickers', label: '🔥 Hot Tickers',  icon: '🔥', path: '/congress/tickers' },
    ],
  },
  {
    id: 'market_intel',
    label: 'Market Intelligence',
    icon: '🎯',
    status: 'live',
    description: 'Options-weighted multi-factor stock ranking across 1W, 1M, and 3M time horizons.',
    subOptions: [
      { id: 'scan',   label: '🎯 Ranked Picks',    icon: '🎯', path: '/market_intel/scan' },
      { id: 'market', label: '🌐 Market Overview', icon: '🌐', path: '/market_intel/market' },
    ],
  },
  {
    id: 'institutional',
    label: '13F Holdings',
    icon: '🏛',
    status: 'live',
    description: 'Institutional ownership from 13F filings — top holders, position changes, and fund flow.',
    subOptions: [
      { id: 'holders',  label: '🏛 Top Holders', icon: '🏛', path: '/institutional/holders' },
      { id: 'flow',     label: '🌊 Fund Flow',   icon: '🌊', path: '/institutional/flow' },
      { id: 'screener', label: '🔎 Screener',    icon: '🔎', path: '/institutional/screener' },
    ],
  },
  {
    id: 'portfolio',
    label: 'Portfolio Tracker',
    icon: '💼',
    status: 'live',
    description: 'Track positions, cost basis, unrealized P&L, and portfolio allocation.',
    subOptions: [
      { id: 'holdings', label: '💼 Holdings',    icon: '💼', path: '/portfolio/holdings' },
      { id: 'summary',  label: '📊 P&L Summary', icon: '📊', path: '/portfolio/summary' },
    ],
  },
  {
    id: 'alerts',
    label: 'Alerts & Watchlist',
    icon: '🔔',
    status: 'live',
    description: 'Price alerts and watchlist with signal notifications.',
    subOptions: [
      { id: 'watchlist', label: '👁 Watchlist',    icon: '👁', path: '/alerts/watchlist' },
      { id: 'alerts',    label: '🔔 Price Alerts', icon: '🔔', path: '/alerts/alerts' },
    ],
  },
]
